spring.application.name=lab_emt

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/lab1_emt
spring.datasource.username=postgres
spring.datasource.password=nova123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

accommodation.stats.refresh.cron=0 * * * * *




spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.locations=classpath:db/migration
#spring.profiles.active=h2